spring:
  application:
    name: aether-backend
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require&currentSchema=aether&prepareThreshold=0}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        default_schema: aether
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    schemas: aether
    default-schema: aether
    baseline-on-migrate: true
    baseline-version: 2

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always