spring:
  application:
    name: aether-backend
  profiles:
    active: dev

---
# Profilo di Sviluppo Locale collegato a Supabase
spring:
  config:
    activate:
      on-profile: dev
  logging:
    level:
      org.hibernate.SQL: DEBUG
  datasource:
    url: ${DB_URL:jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres.uswqqwtlcpkbxydczkyr}
    password: ${DB_PASSWORD:postgresits.}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always