spring:
  application:
    name: aether-backend
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres.uswqqwtlcpkbxydczkyr}
    password: ${DB_PASSWORD:postgresits.}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always